### PR TITLE
updated versions

### PR DESCRIPTION
**Pull request by ChipNowacek**
I know this doesn’t help much. It’s my first attempt. I’m a noob. I’m trying to trace the source of:
> Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to clojure.lang.Associative
>	at clojure.lang.RT.assoc(RT.java:792)
>	at clojure.core$assoc__4371.invokeStatic(core.clj:191)
>	at clojure.core$assoc__4371.invoke(core.clj:190)
>	at instaparse.reduction$apply_standard_reductions$iter__241__245$fn__246.invoke(reduction.clj:54)
>	at clojure.lang.LazySeq.sval(LazySeq.java:40)
>	at clojure.lang.LazySeq.seq(LazySeq.java:49)
>	at clojure.lang.RT.seq(RT.java:521)
>	at clojure.core$seq__4357.invokeStatic(core.clj:137)
>	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
>	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
>	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
>	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
>	at clojure.core$reduce.invokeStatic(core.clj:6545)
>	at clojure.core$into.invokeStatic(core.clj:6610)
>	at clojure.core$into.invoke(core.clj:6604)
>	at instaparse.reduction$apply_standard_reductions.invokeStatic(reduction.clj:52)
>	at instaparse.reduction$apply_standard_reductions.invoke(reduction.clj:48)
>	at instaparse.cfg$build_parser_from_combinators.invokeStatic(cfg.clj:292)
>	at instaparse.cfg$build_parser_from_combinators.invoke(cfg.clj:288)
>	at instaparse.core$parser.invokeStatic(core.clj:248)
>	at instaparse.core$parser.doInvoke(core.clj:171)
>	at clojure.lang.RestFn.invoke(RestFn.java:486)
>	at docopt.core$docopt.invokeStatic(core.clj:155)
>	at docopt.core$docopt.invoke(core.clj:140)
>	at docopt.core$docopt.invokeStatic(core.clj:150)
>	at docopt.core$docopt.invoke(core.clj:140)

### CODE REVIEW

**Comment by ChipNowacek** [comment]
Just in case, I've opened an [instaparse issue](https://github.com/Engelberg/instaparse/issues/157)

**Comment by carocad** [comment]
@ChipNowacek my most sincere apology.

I developed this when I was learning clojure but didn't to keep it up to date as nobody seemed to be using it. I have some free time at the moment so I will try to see what I can do but I dont make any promises, though.

If you are willing to help I would be more than happy to guide you through it.

**Comment by ChipNowacek** [comment]
@carocad No apologies necessary. Thanks for doing it.

Yes, I'd be willing to help. I'm pretty new so patience would be required.

**Comment by ChipNowacek** [comment]
May I ask: would you ever use tools.cli over docopt? If so, when?

**Comment by carocad** [comment]
@ChipNowacek I would advice you to first do some experiments with Instaparse. There is quite a lot of documentation so start there. Also take a look at `regexp` in general. `regex101.com` is quite a good website for that.

As for when to use tools.cli over docopt. The most obvious is if you already have something in tools.cli or if you are more familiar with it. In general, docopt is most useful whenever your command line interface its complex since it allows you to express it in a very concise and clear way. Assuming that somebody has never used neither of them and that you want to have a small cli then both options are equal (for me). The more complex it gets the more I would incline myself towards docopt.

**Comment by ChipNowacek** [comment]
@carocad Thanks. Though I'm good with regex, I know little of Instaparse. I'll start poking around there.

**Comment by carocad** [comment]
@ChipNowacek I am glad to tell you that I found some time to refactor the code. You can check it out at https://github.com/carocad/docopt.clj/tree/refactor specially the `core` file where there are some examples. Check it out and let me know your comments ;)

**Comment by ChipNowacek** [comment]
Cool. Thanks. I'm pulling now.

**Comment by carocad** [comment]
@ChipNowacek I am closing this PR.

Please open an issue with the description of the input/output that you expect docopt to process and we can move from there.

If you want to improve docopt you are more than welcome to help do so :) PR are welcome

**Comment by ChipNowacek** [comment]
Thanks. I'm working with it, just slowly.

**Pull request closed without merging**
